name: Build and Push Nodejs Docker Image


on:
  push:
     branches:
       - main
jobs:
   build:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name:  Set up Docker 
      - uses: docker/setup-buildx-actions@v3
      - name: Log in to Docker ### YamlMime:Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my_node_app:v1
